# Generated by Django 2.2.6 on 2019-10-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('UserName', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
